# These are just tentative formats


# Inputs
query: "example/example_submission.tsv"
subject: "example/example_gs.tsv"
ground_truth: "example/example_gs.tsv"

# Outputs
novel_implementation_output: "novel_implementation_output.tsv"
post_processing_output: "post_processing_output.tsv"
performance_report_output: "performance_report_output.tsv"
